package de.ait.finbot.model;

public enum StatusMessage {
    NONE,
    WAITING_CATEGORY,
    WAITING_EXPENSE,
    WAITING_ID_TO_DELETE,
    WAITING_ID_TO_EDIT,
    WAITING_NEW_NAME_EXPENSE_TO_EDIT,
    PUT_NEW_NAME_EXPENSE,
    WAITING_WHAT_EXPENSE_TO_EDIT,
    PUT_NEW_AMOUNT_EXPENSE,
    PUT_NEW_DATE_EXPENSE,
    PUT_NEW_CATEGORY_EXPENSE
}
