package de.ait.finbot.model;

public enum StatusMessage {
    WAITING_CATEGORY,
    WAITING_EXPENSE,
    WAITING_ID_TO_DELETE,
    WAITING_ID_TO_EDIT,
    WAITING_NAME_TO_EDIT,
    WAITING_NAME_TO_DELETE,
    PUT_NEW_NAME_EXPENSE,
    WAITING_WHAT_EXPENSE_TO_EDIT,
    PUT_NEW_AMOUNT_EXPENSE,
    PUT_NEW_DATE_EXPENSE,
    PUT_NEW_CATEGORY_EXPENSE,
    WAITING_ID_CATEGORY_TO_DELETE
}
